drop database JeuxDB
CREATE DATABASE JeuxDB;
USE JeuxDB;
CREATE TABLE Laideurboard (
                              id_laideurboard INT AUTO_INCREMENT PRIMARY KEY,
                              id_mots VARCHAR(255) NOT NULL,
                              nom_joueur VARCHAR(255) NOT NULL,
                              score INT NOT NULL,
                              FOREIGN KEY (id_mots) REFERENCES DICKO(mots) ON DELETE CASCADE
);
CREATE TABLE DICKO (
                       id_mot INT AUTO_INCREMENT PRIMARY KEY,
                       mot VARCHAR(5) NOT NULL
);
INSERT INTO DICKO (mot) VALUES
                            ('ABIDE'),
                            ('ABORD'),
                            ('ACIDE'),
                            ('AIDER'),
                            ('AIGRE'),
                            ('ALOUE'),
                            ('AMPLE'),
                            ('ANCRE'),
                            ('ANGLE'),
                            ('ASILE'),
                            ('ATTIR'),
                            ('AVIDE'),
                            ('AVION'),
                            ('CACHE'),
                            ('CAIRE'),
                            ('CEDER'),
                            ('CHIFF'),
                            ('CHIME'),
                            ('CHOSE'),
                            ('CIBLE'),
                            ('CINQE'),
                            ('CLAVE'),
                            ('CLICS'),
                            ('COCHE'),
                            ('COUDE'),
                            ('CRIER'),
                            ('CRISE'),
                            ('CRANE'),
                            ('CUIRS'),
                            ('DENTS'),
                            ('DINER'),
                            ('DORMI'),
                            ('DOSER'),
                            ('DOUCE'),
                            ('DRAME'),
                            ('DRAPE'),
                            ('ENVIE'),
                            ('ETAPE'),
                            ('EVITE'),
                            ('EXILS'),
                            ('FABLE'),
                            ('FEINT'),
                            ('FERME'),
                            ('FICHE'),
                            ('FIGER'),
                            ('FILLE'),
                            ('FLORE'),
                            ('FOINS'),
                            ('FOLIE'),
                            ('FONCE'),
                            ('FRISE'),
                            ('FUIRS'),
                            ('FUITE'),
                            ('GAGNE'),
                            ('GARDE'),
                            ('GLACE'),
                            ('GOUGE'),
                            ('GOUTE'),
                            ('GRISE'),
                            ('GRIVE'),
                            ('GUITI'),
                            ('HAMPE'),
                            ('HANTE'),
                            ('HUMER'),
                            ('HURLE'),
                            ('HEROS'),
                            ('IDEES'),
                            ('ILLES'),
                            ('ISSUE'),
                            ('IVRES'),
                            ('JANTE'),
                            ('JETER'),
                            ('JETTE'),
                            ('JOUER'),
                            ('KALOS'),
                            ('KILOS'),
                            ('LAINE'),
                            ('LICES'),
                            ('LIMON'),
                            ('LIRIS'),
                            ('LIVRE'),
                            ('MAINS'),
                            ('METEO'),
                            ('MOTIF'),
                            ('MOULT'),
                            ('PIEDS'),
                            ('PORTE'),
                            ('SAGES'),
                            ('TERRE'),
                            ('VAGUE'),
                            ('VALET'),
                            ('VIDES'),
                            ('VIVRE');